apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fast-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NicoGo/ArgoCDManagement.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fast-api

  syncPolicy: # To create the namespace automatically
    syncOptions:
      - CreateNamespace=true

    automated: # will be done every 3 minutes
      selfHeal: true
      prune: true # prune is the cleaning method