apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nicolasgo/fast-api:27
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
